name: Update README with External Contributions

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch: # Allow manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install @octokit/core

      - name: Run Update Script
        run: node update-readme.js

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update README with latest external contributions"
          branch: main
